version: '3.7'
services:
  mysql:
    # Don't use latest (MySQL Server 8.0) as we cannot currently authenticate to it
    image: mysql:5.7
    restart: always
    ports: ['3306:3306']
    environment:
      # - MYSQL_ROOT_PASSWORD=bbk4k77JKH88g54
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=travis
      - MYSQL_PASSWORD=bbk4k77JKH88g54
  postgres:
    image: postgres:latest
    restart: always
    ports: ['5432:5432']
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports: ['1433:1433']
    environment:
      - MSSQL_PID=Developer
      - SA_PASSWORD=bbk4k77JKH88g54
      - ACCEPT_EULA=Y
  # You'll need to have a login for https://container-registry.oracle.com and have
  # accepted their terms & conditions. Then prior to running 'docker-compose up -d' you
  # will need to run 'docker login container-registry.oracle.com' to pull the Oracle Database image.
  # Also, Oracle takes considerably more resources.
#  oracle:
#    image: container-registry.oracle.com/database/standard:12.1.0.2
#    ports:
#      - 1521:1521
#      - 8080:8080
#      - 5500:5500
#    environment:
#      - DB_SID=travis
#      - DB_PASSWD=bbk4k77JKH88g54
#      - USERNAME=travis
#      - PASSWORD=bbk4k77JKH88g54
